import { ownerScope } from '../utils/ownership.js';
import Patient from '../models/Patient.js'; import Visit from '../models/Visit.js'; import Payment from '../models/Payment.js'; import SpectacleOrder from '../models/SpectacleOrder.js'; import { nextPublicId } from '../utils/ids.js'; import { ApiError } from '../utils/ApiError.js'; import { getPagination, paginationMeta } from '../utils/pagination.js';
export async function createPatient(input, userId) { return Patient.create({ ...input, ...ownerScope(userId), patientId: await nextPublicId('P') }); }
export async function listPatients(query, userId) { const { page, limit, skip } = getPagination(query); const term = query.search?.trim(); const filter = { ...ownerScope(userId), isActive: true, ...(term && { $or: [{ patientId: new RegExp(`^${escape(term)}$`, 'i') }, { name: new RegExp(escape(term), 'i') }, { mobile: new RegExp(escape(term), 'i') }] }) }; const [data, total] = await Promise.all([Patient.find(filter).sort({ createdAt: -1 }).skip(skip).limit(limit).lean(), Patient.countDocuments(filter)]); return { data, pagination: paginationMeta({ page, limit, total }) }; }
const escape = (text) => text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
export async function getPatient(id, userId, active = true) { const doc = await Patient.findOne({ ...ownerScope(userId), _id: id, ...(active && { isActive: true }) }); if (!doc) throw new ApiError(404, 'Patient not found'); return doc; }
export async function updatePatient(id, input, userId) { const entries = Object.entries(input); const update = { $set: Object.fromEntries(entries.filter(([, value]) => value !== null)), $unset: Object.fromEntries(entries.filter(([, value]) => value === null).map(([key]) => [key, 1])) }; const doc = await Patient.findOneAndUpdate({ ...ownerScope(userId), _id: id, isActive: true }, update, { new: true, runValidators: true }); if (!doc) throw new ApiError(404, 'Patient not found'); return doc; }
export async function patientDetails(id, userId) { const patient = await getPatient(id, userId); const [latestVisit, activeOrder, payments, recentVisits] = await Promise.all([Visit.findOne({ ...ownerScope(userId), patient: id }).sort({ visitDate: -1 }).lean(), SpectacleOrder.findOne({ ...ownerScope(userId), patient: id, status: { $nin: ['DELIVERED', 'CANCELLED'] } }).sort({ createdAt: -1 }).lean(), Payment.aggregate([{ $match: { ...ownerScope(userId), patient: patient._id, status: 'COMPLETED' } }, { $group: { _id: null, totalPaid: { $sum: '$amount' } } }]), Visit.find({ ...ownerScope(userId), patient: id }).sort({ visitDate: -1 }).limit(5).lean()]); const bills = await Promise.all([Visit.aggregate([{ $match: { ...ownerScope(userId), patient: patient._id } }, { $group: { _id: null, total: { $sum: '$charges.total' } } }]), SpectacleOrder.aggregate([{ $match: { ...ownerScope(userId), patient: patient._id, status: { $ne: 'CANCELLED' } } }, { $group: { _id: null, total: { $sum: '$totalAmount' } } }])]); const totalBilled = (bills[0][0]?.total || 0) + (bills[1][0]?.total || 0); const totalPaid = payments[0]?.totalPaid || 0; return { patient, latestVisit, latestEyeExamination: latestVisit?.eyeExamination, latestPrescription: latestVisit?.medicines || [], activeSpectacleOrder: activeOrder, paymentSummary: { totalBilled, totalPaid, due: Math.max(0, totalBilled - totalPaid) }, recentVisits }; }
export async function timeline(id, userId) { await getPatient(id, userId); const [visits, orders, payments] = await Promise.all([Visit.find({ ...ownerScope(userId), patient: id }).sort({ visitDate: -1 }).lean(), SpectacleOrder.find({ ...ownerScope(userId), patient: id }).sort({ createdAt: -1 }).lean(), Payment.find({ ...ownerScope(userId), patient: id }).sort({ paymentDate: -1 }).lean()]); return [...visits.map((x) => ({ type: 'VISIT', date: x.visitDate, data: x })), ...orders.map((x) => ({ type: 'SPECTACLE_ORDER', date: x.createdAt, data: x })), ...payments.map((x) => ({ type: 'PAYMENT', date: x.paymentDate, data: x }))].sort((a, b) => new Date(b.date) - new Date(a.date)); }
