import { z } from 'zod';
const id = z.string().regex(/^[a-f\d]{24}$/i, 'Invalid ID'); const number = z.coerce.number().finite().min(0); const positive = z.coerce.number().finite().positive(); const optionalDate = z.coerce.date().optional();
const registrationEye = z.object({ unaidedVision: z.string().trim().max(40).optional(), correctedVision: z.string().trim().max(40).optional(), pinholeVision: z.string().trim().max(40).optional(), nearVision: z.string().trim().max(40).optional(), sph: z.number().finite().min(-50).max(50).optional(), cyl: z.number().finite().min(-50).max(50).optional(), axis: z.number().finite().min(0).max(180).optional(), add: z.number().finite().min(-50).max(50).optional(), iop: z.number().finite().min(0).max(100).optional() });
export const investigationSchema = z.object({ rightEye: registrationEye.optional(), leftEye: registrationEye.optional(), pd: z.number().finite().min(0).max(100).optional(), remarks: z.string().max(2000).optional() });
export const patientInput = z.object({ name: z.string().trim().min(1).max(120), mobile: z.string().trim().regex(/^[+\d\s()-]{7,20}$/).optional(), age: z.coerce.number().int().min(0).max(130).optional(), dateOfBirth: optionalDate, gender: z.enum(['MALE','FEMALE','OTHER','PREFER_NOT_TO_SAY']).optional(), address: z.string().max(500).optional(), bloodGroup: z.string().max(10).optional(), allergies: z.string().max(1000).optional(), medicalNotes: z.string().max(3000).optional(), investigation: investigationSchema.optional() });
// PATCH accepts null to explicitly clear an optional patient field.
export const patientPatch = patientInput.partial().extend(Object.fromEntries(Object.entries(patientInput.shape).filter(([key]) => key !== 'name').map(([key, value]) => [key, value.nullable()])));
const eye = registrationEye.extend({ sph: z.coerce.number().finite().min(-50).max(50).optional(), cyl: z.coerce.number().finite().min(-50).max(50).optional(), axis: z.coerce.number().min(0).max(180).optional(), va: z.string().max(20).optional(), add: z.coerce.number().finite().min(-50).max(50).optional() });
export const visitInput = z.object({ patient: id, visitDate: optionalDate, complaint: z.string().max(2000).optional(), symptoms: z.array(z.string().trim().min(1).max(100)).max(30).optional(), diagnoses: z.array(z.object({ name: z.string().trim().min(1).max(200), eye: z.enum(['OD', 'OS', 'OU']), status: z.enum(['PROVISIONAL', 'CONFIRMED']) })).max(20).optional(), eyeExamination: z.object({ rightEye: eye.optional(), leftEye: eye.optional(), pd: z.coerce.number().min(0).max(100).optional(), remarks: z.string().max(2000).optional() }).optional(), doctorNotes: z.string().max(5000).optional(), medicines: z.array(z.object({ medicine: id.optional(), medicineName: z.string().trim().min(1).max(200).optional(), quantity: z.coerce.number().int().min(1), dosage: z.string().max(100).optional(), frequency: z.string().max(100).optional(), duration: z.string().max(100).optional(), instructions: z.string().max(500).optional(), strength: z.string().max(100).optional(), eye: z.enum(['OD', 'OS', 'OU', 'NA']).optional(), unitPrice: number.optional() }).refine((x) => x.medicine || x.medicineName, 'Medicine or medicineName required')).default([]), charges: z.object({ consultation: number.optional(), other: number.optional(), discount: number.optional() }).optional(), followUpDate: optionalDate, remarks: z.string().max(3000).optional() });
export const medicineInput = z.object({ name: z.string().trim().min(1).max(200), genericName: z.string().max(200).optional(), unit: z.string().max(40).optional(), defaultPrice: number.optional(), description: z.string().max(1000).optional(), isActive: z.boolean().optional() });
export const orderInput = z.object({ patient: id, visit: id.optional(), pd: z.coerce.number().min(0).max(100).optional(), rightEye: eye.optional(), leftEye: eye.optional(), frameName: z.string().max(200).optional(), framePrice: number.optional(), lensType: z.string().max(200).optional(), lensPrice: number.optional(), otherCharges: number.optional(), discount: number.optional(), deliveryDate: optionalDate, notes: z.string().max(2000).optional() });
export const orderPatch = orderInput.omit({ patient: true, visit: true }).extend({ status: z.enum(['ORDERED','IN_PROCESS','READY','DELIVERED','CANCELLED']).optional() });
export const paymentInput = z.object({ patient: id, visit: id.optional(), spectacleOrder: id.optional(), amount: positive, paymentMethod: z.enum(['CASH','UPI','CARD','OTHER']), paymentDate: optionalDate, referenceNumber: z.string().max(200).optional(), notes: z.string().max(1000).optional() });
export const loginInput = z.object({ email: z.string().email(), password: z.string().min(8).max(200) });
export const passwordInput = z.object({ currentPassword: z.string().min(8), newPassword: z.string().min(8).max(200) });

export const paymentPatch = paymentInput.pick({ amount: true, paymentMethod: true, paymentDate: true, referenceNumber: true, notes: true }).partial().extend({ editNote: z.string().trim().min(1, "Reason for editing is required").max(2000) });
